set(_CATKIN_CURRENT_PACKAGE "baxter_gui")
set(baxter_gui_VERSION "0.1.0")
set(baxter_gui_MAINTAINER "N <N@gmail.com>")
set(baxter_gui_PACKAGE_FORMAT "1")
set(baxter_gui_BUILD_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(baxter_gui_BUILD_EXPORT_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(baxter_gui_BUILDTOOL_DEPENDS "catkin")
set(baxter_gui_BUILDTOOL_EXPORT_DEPENDS )
set(baxter_gui_EXEC_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(baxter_gui_RUN_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(baxter_gui_TEST_DEPENDS )
set(baxter_gui_DOC_DEPENDS )
set(baxter_gui_DEPRECATED "")