// Generated by gencpp from file baxter_gui/send_commandRequest.msg
// DO NOT EDIT!


#ifndef BAXTER_GUI_MESSAGE_SEND_COMMANDREQUEST_H
#define BAXTER_GUI_MESSAGE_SEND_COMMANDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baxter_gui
{
template <class ContainerAllocator>
struct send_commandRequest_
{
  typedef send_commandRequest_<ContainerAllocator> Type;

  send_commandRequest_()
    : start()  {
    }
  send_commandRequest_(const ContainerAllocator& _alloc)
    : start(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _start_type;
  _start_type start;




  typedef boost::shared_ptr< ::baxter_gui::send_commandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_gui::send_commandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct send_commandRequest_

typedef ::baxter_gui::send_commandRequest_<std::allocator<void> > send_commandRequest;

typedef boost::shared_ptr< ::baxter_gui::send_commandRequest > send_commandRequestPtr;
typedef boost::shared_ptr< ::baxter_gui::send_commandRequest const> send_commandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_gui::send_commandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_gui::send_commandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_gui

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_gui::send_commandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_gui::send_commandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_gui::send_commandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_gui::send_commandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_gui::send_commandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_gui::send_commandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_gui::send_commandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34ede85548daeef03201b4a532fb98e1";
  }

  static const char* value(const ::baxter_gui::send_commandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34ede85548daeef0ULL;
  static const uint64_t static_value2 = 0x3201b4a532fb98e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_gui::send_commandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_gui/send_commandRequest";
  }

  static const char* value(const ::baxter_gui::send_commandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_gui::send_commandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string start\n\
";
  }

  static const char* value(const ::baxter_gui::send_commandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_gui::send_commandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct send_commandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_gui::send_commandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_gui::send_commandRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_GUI_MESSAGE_SEND_COMMANDREQUEST_H
