// Generated by gencpp from file baxter_gui/send_command.msg
// DO NOT EDIT!


#ifndef BAXTER_GUI_MESSAGE_SEND_COMMAND_H
#define BAXTER_GUI_MESSAGE_SEND_COMMAND_H

#include <ros/service_traits.h>


#include <baxter_gui/send_commandRequest.h>
#include <baxter_gui/send_commandResponse.h>


namespace baxter_gui
{

struct send_command
{

typedef send_commandRequest Request;
typedef send_commandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct send_command
} // namespace baxter_gui


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::baxter_gui::send_command > {
  static const char* value()
  {
    return "c856a68efb24b22273f35f912e1cb37c";
  }

  static const char* value(const ::baxter_gui::send_command&) { return value(); }
};

template<>
struct DataType< ::baxter_gui::send_command > {
  static const char* value()
  {
    return "baxter_gui/send_command";
  }

  static const char* value(const ::baxter_gui::send_command&) { return value(); }
};


// service_traits::MD5Sum< ::baxter_gui::send_commandRequest> should match 
// service_traits::MD5Sum< ::baxter_gui::send_command > 
template<>
struct MD5Sum< ::baxter_gui::send_commandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_gui::send_command >::value();
  }
  static const char* value(const ::baxter_gui::send_commandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_gui::send_commandRequest> should match 
// service_traits::DataType< ::baxter_gui::send_command > 
template<>
struct DataType< ::baxter_gui::send_commandRequest>
{
  static const char* value()
  {
    return DataType< ::baxter_gui::send_command >::value();
  }
  static const char* value(const ::baxter_gui::send_commandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::baxter_gui::send_commandResponse> should match 
// service_traits::MD5Sum< ::baxter_gui::send_command > 
template<>
struct MD5Sum< ::baxter_gui::send_commandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_gui::send_command >::value();
  }
  static const char* value(const ::baxter_gui::send_commandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_gui::send_commandResponse> should match 
// service_traits::DataType< ::baxter_gui::send_command > 
template<>
struct DataType< ::baxter_gui::send_commandResponse>
{
  static const char* value()
  {
    return DataType< ::baxter_gui::send_command >::value();
  }
  static const char* value(const ::baxter_gui::send_commandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BAXTER_GUI_MESSAGE_SEND_COMMAND_H
